// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkZnv-R-otmmizFBXXU9EcCS-3yhIkg8g',
    appId: '1:195814278870:web:650e7595014d402225eb77',
    messagingSenderId: '195814278870',
    projectId: 'remind-diary-e6b0b',
    authDomain: 'remind-diary-e6b0b.firebaseapp.com',
    storageBucket: 'remind-diary-e6b0b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe_v22TpJPfzY-AJouuIDt71E88z7iG0M',
    appId: '1:195814278870:android:9bd4cb8972bc805c25eb77',
    messagingSenderId: '195814278870',
    projectId: 'remind-diary-e6b0b',
    storageBucket: 'remind-diary-e6b0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnxklcD-s2HK-8AQ63GsdtX3fwCagRhss',
    appId: '1:195814278870:ios:4b014cc1fbaad9dd25eb77',
    messagingSenderId: '195814278870',
    projectId: 'remind-diary-e6b0b',
    storageBucket: 'remind-diary-e6b0b.appspot.com',
    iosClientId: '195814278870-rgof46nso3i422e34gjmbm34rnpr1pao.apps.googleusercontent.com',
    iosBundleId: 'com.example.reminddiary',
  );
}
